<?php
header('Content-Type: application/json');

session_start();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $year = $_POST['year'] ?? '';
    $month = $_POST['month'] ?? '';
    $title = $_POST['title'] ?? '';
    $summary = $_POST['summary'] ?? '';
    $pdfFile = $_FILES['pdfFile'] ?? null;
    $coverBase64 = $_POST['coverImageBase64'] ?? '';

    if (empty($year) || empty($month) || empty($title) || empty($summary)) {
        echo json_encode(['success' => false, 'message' => 'Semua kolom teks harus diisi.']);
        exit;
    }

    $jsonFile = '../assets/json/data-wmagz.json';
    $currentData = [];
    if (file_exists($jsonFile)) {
        $jsonContent = file_get_contents($jsonFile);
        $currentData = json_decode($jsonContent, true) ?? ['magazines' => []];
    }

    if (!isset($currentData['magazines'])) {
        $currentData['magazines'] = [];
    }

    $pdfPath = '';
    
    // 1. Process PDF File
    if ($pdfFile && $pdfFile['error'] === UPLOAD_ERR_OK) {
        $pdfUploadDir = "../assets/pdf/wmagz/$year/";
        if (!is_dir($pdfUploadDir)) {
            mkdir($pdfUploadDir, 0777, true);
        }

        // e.g. "wmagz_January.pdf"
        $pdfFilename = "wmagz_{$month}.pdf";
        $targetPdfPath = $pdfUploadDir . $pdfFilename;
        $pdfPath = "assets/pdf/wmagz/$year/$pdfFilename";

        if (!move_uploaded_file($pdfFile['tmp_name'], $targetPdfPath)) {
            echo json_encode(['success' => false, 'message' => 'Gagal mengunggah file PDF.']);
            exit;
        }
    } else {
         echo json_encode(['success' => false, 'message' => 'File PDF wajib diunggah.']);
         exit;
    }

    $imagePath = '';

    // 2. Process Base64 Cover Image (Generated by PDF.js on client)
    if (!empty($coverBase64)) {
        $imgUploadDir = "../assets/image/wmagz/$year/";
        if (!is_dir($imgUploadDir)) {
            mkdir($imgUploadDir, 0777, true);
        }

        $imgFilename = "cover_{$month}.webp";
        $targetImgPath = $imgUploadDir . $imgFilename;
        $imagePath = "assets/image/wmagz/$year/$imgFilename";

        // Extract base64
        if (preg_match('/^data:image\/(\w+);base64,/', $coverBase64, $type)) {
            $coverBase64 = substr($coverBase64, strpos($coverBase64, ',') + 1);
            $type = strtolower($type[1]); // jpg, png, etc

            $coverData = base64_decode($coverBase64);

            if ($coverData !== false) {
                $sourceImage = imagecreatefromstring($coverData);
                if ($sourceImage !== false) {
                    imagewebp($sourceImage, $targetImgPath, 80);
                    imagedestroy($sourceImage);
                }
            }
        }
    } else {
         echo json_encode(['success' => false, 'message' => 'Gagal membuat kover dari PDF.']);
         exit;
    }

    // Assign to structure
    if (!isset($currentData['magazines'][$year])) {
        $currentData['magazines'][$year] = [];
    }

    $currentData['magazines'][$year][$month] = [
        'title' => $title,
        'summary' => $summary,
        'coverImage' => $imagePath,
        'link' => $pdfPath
    ];

    if (file_put_contents($jsonFile, json_encode($currentData, JSON_PRETTY_PRINT))) {
        echo json_encode(['success' => true, 'message' => 'Edisi majalah PDF berhasil ditambahkan!']);
    } else {
        echo json_encode(['success' => false, 'message' => 'Gagal menyimpan ke data JSON.']);
    }

} else {
    echo json_encode(['success' => false, 'message' => 'Invalid request method.']);
}
?>
